import type { Movie } from "./types";
import { slugify } from "@/libs/utils";

export const NOW_SHOWING: Movie[] = [
  {
    id: "0",
    title: "Interstellar",
    slug: slugify("Interstellar"),
    genre: "Sci-Fi",
    rating: 8.7,
    duration: 169,
    src: "/images/hero-interstellar.jpg",
    synopsis:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival, as Earth becomes increasingly inhospitable.",
    director: "Christopher Nolan",
    cast: [
      { name: "Matthew McConaughey", role: "Cooper", src: "https://i.pravatar.cc/300?img=12" },
      { name: "Anne Hathaway", role: "Brand", src: "https://i.pravatar.cc/300?img=20" },
      { name: "Jessica Chastain", role: "Murph", src: "https://i.pravatar.cc/300?img=25" },
    ],
    releaseDate: "2014-11-07",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "1",
    title: "Avengers",
    slug: slugify("Avengers"),
    genre: "Sci-Fi",
    rating: 8.5,
    duration: 143,
    src: "https://i.ebayimg.com/images/g/wy8AAOSwGMFcv5s2/s-l1200.jpg",
    synopsis:
      "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    director: "Joss Whedon",
    cast: [
      { name: "Robert Downey Jr.", role: "Iron Man", src: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Actor_Robert_Downey_Jr._photographed_by_the_California_Department_of_Corrections.jpg" },
      { name: "Chris Evans", role: "Captain America", src: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Chris_Evans_TIFF_2012.jpg" },
      { name: "Mark Ruffalo", role: "The Hulk", src: "https://upload.wikimedia.org/wikipedia/commons/8/81/Mark_Ruffalo_%282007%29.jpg" },
      { name: "Chris Hemsworth", role: "Thor", src: "https://upload.wikimedia.org/wikipedia/commons/9/91/Chris_Hemsworth_by_Gage_Skidmore_2.jpg" },
    ],
    releaseDate: "2012-05-04",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "2",
    title: "Joker",
    slug: slugify("Joker"),
    genre: "Action",
    rating: 8.2,
    duration: 122,
    src: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280w/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1669120603.jpg?c=2",
    synopsis:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    director: "Todd Phillips",
    cast: [
      { name: "Joaquin Phoenix", role: "Arthur Fleck", src: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Joaquin_Phoenix%2C_2014.jpg" },
      { name: "Robert De Niro", role: "Murray Franklin", src: "https://upload.wikimedia.org/wikipedia/commons/8/82/Robert_De_Niro_KVIFF_portrait.jpg" },
      { name: "Zazie Beetz", role: "Sophie Dumond", src: "https://upload.wikimedia.org/wikipedia/commons/5/51/Zazie_Beetz_by_Gage_Skidmore.jpg" },
    ],
    releaseDate: "2019-10-04",
    ageRating: "R",
    language: "English",
  },
  {
    id: "3",
    title: "Divided",
    slug: slugify("Divided"),
    genre: "Thriller",
    rating: 7.8,
    duration: 108,
    src: "https://cdn.dribbble.com/userupload/35223132/file/original-ef853765fc767c6f1d0648662220c2a3.jpg?resize=752x&vertical=center",
    synopsis:
      "A group of strangers find themselves trapped in a mysterious building, only to realize they are all connected by a dark secret.",
    director: "James DeMonaco",
    cast: [
      { name: "Frank Grillo", role: "Leo Barnes", src: "https://i.pravatar.cc/300?img=11" },
      { name: "Maggie Q", role: "Elena", src: "https://i.pravatar.cc/300?img=5" },
      { name: "Sergio Peris-Mencheta", role: "Caleb Tucker", src: "https://i.pravatar.cc/300?img=12" },
    ],
    releaseDate: "2024-03-15",
    ageRating: "R",
    language: "English",
  },
  {
    id: "4",
    title: "Inception",
    slug: slugify("Inception"),
    genre: "Action",
    rating: 8.8,
    duration: 148,
    src: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    synopsis:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    director: "Christopher Nolan",
    cast: [
      { name: "Leonardo DiCaprio", role: "Dom Cobb", src: "https://upload.wikimedia.org/wikipedia/commons/7/71/Leonardo_DiCaprio.jpg" },
      { name: "Joseph Gordon-Levitt", role: "Arthur", src: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Joseph_Gordon-Levitt_by_Gage_Skidmore_2.jpg" },
      { name: "Elliot Page", role: "Ariadne", src: "https://i.pravatar.cc/300?img=32" },
      { name: "Tom Hardy", role: "Eames", src: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Tom_Hardy_by_Gage_Skidmore_in_2018.jpg" },
    ],
    releaseDate: "2010-07-16",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "5",
    title: "The Dark Knight",
    slug: slugify("The Dark Knight"),
    genre: "Action",
    rating: 9.0,
    duration: 152,
    src: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
    synopsis:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    director: "Christopher Nolan",
    cast: [
      { name: "Christian Bale", role: "Batman", src: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Christianbale.jpg" },
      { name: "Heath Ledger", role: "The Joker", src: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Heath_Ledger_face.jpg" },
      { name: "Aaron Eckhart", role: "Harvey Dent", src: "https://i.pravatar.cc/300?img=53" },
      { name: "Maggie Gyllenhaal", role: "Rachel Dawes", src: "https://i.pravatar.cc/300?img=23" },
    ],
    releaseDate: "2008-07-18",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "6",
    title: "Oppenheimer",
    slug: slugify("Oppenheimer"),
    genre: "Drama",
    rating: 8.4,
    duration: 180,
    src: "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
    synopsis:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    director: "Christopher Nolan",
    cast: [
      { name: "Cillian Murphy", role: "J. Robert Oppenheimer", src: "https://upload.wikimedia.org/wikipedia/commons/6/6e/MKr347645_Cillian_Murphy_%28Small_Things_Like_These%2C_Berlinale_2024%29.jpg" },
      { name: "Emily Blunt", role: "Kitty Oppenheimer", src: "https://upload.wikimedia.org/wikipedia/commons/0/06/Emily_Blunt_%2832056670378%29.jpg" },
      { name: "Matt Damon", role: "Leslie Groves", src: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Matt_Damon_2014.jpg" },
      { name: "Robert Downey Jr.", role: "Lewis Strauss", src: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Actor_Robert_Downey_Jr._photographed_by_the_California_Department_of_Corrections.jpg" },
    ],
    releaseDate: "2023-07-21",
    ageRating: "R",
    language: "English",
  },
];

export const COMING_SOON: Movie[] = [
  {
    id: "7",
    title: "Final Destination",
    slug: slugify("Final Destination"),
    genre: "Action • Adventure",
    rating: 0,
    duration: 0,
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYW-jtF1yrYxp4mqeCvrMGNYwIvEIDCAPUCYQWJ1WyKvbCKBvyMkbJX69I&s=10",
    synopsis:
      "A new installment in the Final Destination franchise, where death finds creative ways to claim its victims.",
    director: "Zack Lipovsky",
    cast: [
      { name: "Brec Bassinger", role: "Lead Role", src: "https://i.pravatar.cc/300?img=47" },
      { name: "Tony Todd", role: "William Bludworth", src: "https://i.pravatar.cc/300?img=59" },
    ],
    releaseDate: "2025-05-16",
    ageRating: "R",
    language: "English",
  },
  {
    id: "8",
    title: "The Deep",
    slug: slugify("The Deep"),
    genre: "Horror",
    rating: 0,
    duration: 0,
    src: "https://m.media-amazon.com/images/I/51zbb0xr4GL._AC_UF1000,1000_QL80_.jpg",
    synopsis:
      "A deep-sea exploration turns into a nightmare when the crew encounters an ancient creature lurking in the abyss.",
    director: "James Cameron",
    cast: [
      { name: "Kate Winslet", role: "Dr. Elara Vance", src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Kate_Winslet_at_the_2006_Toronto_International_Film_Festival.jpg/300px-Kate_Winslet_at_the_2006_Toronto_International_Film_Festival.jpg" },
      { name: "Sam Worthington", role: "Captain Marcus Cole", src: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Sam_Worthington%2C_Jennifer_Hawkins_%288491455629%29.jpg" },
    ],
    releaseDate: "2025-12-20",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "9",
    title: "Hercules",
    slug: slugify("Hercules"),
    genre: "Fantasy",
    rating: 0,
    duration: 0,
    src: "https://upload.wikimedia.org/wikipedia/en/6/65/Hercules_%281997_film%29_poster.jpg",
    synopsis:
      "The son of Zeus must prove himself worthy of his place among the gods by completing a series of legendary labors.",
    director: "Brett Ratner",
    cast: [
      { name: "Dwayne Johnson", role: "Hercules", src: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Dwayne_The_Rock_Johnson_2009_portrait.jpg" },
      { name: "Ian McShane", role: "Amphitryon", src: "https://i.pravatar.cc/300?img=60" },
      { name: "Rufus Sewell", role: "Autolycus", src: "https://i.pravatar.cc/300?img=14" },
    ],
    releaseDate: "2025-07-25",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "10",
    title: "Wonder Woman 1984",
    slug: slugify("Wonder Woman 1984"),
    genre: "Action",
    rating: 0,
    duration: 0,
    src: "https://m.media-amazon.com/images/I/51D-7LjfJiL._AC_UF894,1000_QL80_.jpg",
    synopsis:
      "Diana must face two new foes as she navigates the Cold War era of the 1980s while protecting the world from a powerful artifact.",
    director: "Patty Jenkins",
    cast: [
      { name: "Gal Gadot", role: "Diana Prince", src: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Gal_Gadot_by_Gage_Skidmore_2.jpg" },
      { name: "Chris Pine", role: "Steve Trevor", src: "https://i.pravatar.cc/300?img=51" },
      { name: "Kristen Wiig", role: "Barbara Minerva", src: "https://i.pravatar.cc/300?img=25" },
      { name: "Pedro Pascal", role: "Maxwell Lord", src: "https://upload.wikimedia.org/wikipedia/commons/3/33/Pedro_Pascal_by_Gage_Skidmore_2.jpg" },
    ],
    releaseDate: "2025-12-25",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "11",
    title: "Shang-Chi and the Legend of the Ten Rings",
    slug: slugify("Shang-Chi and the Legend of the Ten Rings"),
    genre: "Action",
    rating: 0,
    duration: 0,
    src: "https://m.media-amazon.com/images/I/71M9kkXbmSL._AC_UF894,1000_QL80_.jpg",
    synopsis:
      "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    director: "Destin Daniel Cretton",
    cast: [
      { name: "Simu Liu", role: "Shang-Chi", src: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Simu_Liu_by_Gage_Skidmore.jpg" },
      { name: "Awkwafina", role: "Katy", src: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Awkwafina.png" },
      { name: "Tony Leung", role: "Xu Wenwu", src: "https://i.pravatar.cc/300?img=68" },
    ],
    releaseDate: "2025-11-05",
    ageRating: "PG-13",
    language: "English",
  },
];

export const ALL_MOVIES: Movie[] = [...NOW_SHOWING, ...COMING_SOON];
