import type { Movie } from "./types";
import { slugify } from "@/libs/utils";

export const NOW_SHOWING: Movie[] = [
  {
    id: "1",
    title: "Avengers",
    slug: slugify("Avengers"),
    genre: "Sci-Fi",
    rating: 8.5,
    duration: 143,
    src: "https://i.ebayimg.com/images/g/wy8AAOSwGMFcv5s2/s-l1200.jpg",
    synopsis:
      "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    director: "Joss Whedon",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    releaseDate: "2012-05-04",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "2",
    title: "Joker",
    slug: slugify("Joker"),
    genre: "Action",
    rating: 8.2,
    duration: 122,
    src: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280w/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1669120603.jpg?c=2",
    synopsis:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    releaseDate: "2019-10-04",
    ageRating: "R",
    language: "English",
  },
  {
    id: "3",
    title: "Divided",
    slug: slugify("Divided"),
    genre: "Thriller",
    rating: 7.8,
    duration: 108,
    src: "https://cdn.dribbble.com/userupload/35223132/file/original-ef853765fc767c6f1d0648662220c2a3.jpg?resize=752x&vertical=center",
    synopsis:
      "A group of strangers find themselves trapped in a mysterious building, only to realize they are all connected by a dark secret.",
    director: "James DeMonaco",
    cast: ["Frank Grillo", "Maggie Q", "Sergio Peris-Mencheta"],
    releaseDate: "2024-03-15",
    ageRating: "R",
    language: "English",
  },
  {
    id: "4",
    title: "Inception",
    slug: slugify("Inception"),
    genre: "Action",
    rating: 8.8,
    duration: 148,
    src: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    synopsis:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    releaseDate: "2010-07-16",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "5",
    title: "The Dark Knight",
    slug: slugify("The Dark Knight"),
    genre: "Action",
    rating: 9.0,
    duration: 152,
    src: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
    synopsis:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
    releaseDate: "2008-07-18",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "6",
    title: "Oppenheimer",
    slug: slugify("Oppenheimer"),
    genre: "Drama",
    rating: 8.4,
    duration: 180,
    src: "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
    synopsis:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    releaseDate: "2023-07-21",
    ageRating: "R",
    language: "English",
  },
];

export const COMING_SOON: Movie[] = [
  {
    id: "7",
    title: "Final Destination",
    slug: slugify("Final Destination"),
    genre: "Action • Adventure",
    rating: 0,
    duration: 0,
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYW-jtF1yrYxp4mqeCvrMGNYwIvEIDCAPUCYQWJ1WyKvbCKBvyMkbJX69I&s=10",
    synopsis:
      "A new installment in the Final Destination franchise, where death finds creative ways to claim its victims.",
    director: "Zack Lipovsky",
    cast: ["Brec Bassinger", "Tony Todd"],
    releaseDate: "2025-05-16",
    ageRating: "R",
    language: "English",
  },
  {
    id: "8",
    title: "The Deep",
    slug: slugify("The Deep"),
    genre: "Horror",
    rating: 0,
    duration: 0,
    src: "https://m.media-amazon.com/images/I/51zbb0xr4GL._AC_UF1000,1000_QL80_.jpg",
    synopsis:
      "A deep-sea exploration turns into a nightmare when the crew encounters an ancient creature lurking in the abyss.",
    director: "James Cameron",
    cast: ["Kate Winslet", "Sam Worthington"],
    releaseDate: "2025-12-20",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "9",
    title: "Hercules",
    slug: slugify("Hercules"),
    genre: "Fantasy",
    rating: 0,
    duration: 0,
    src: "https://upload.wikimedia.org/wikipedia/en/6/65/Hercules_%281997_film%29_poster.jpg",
    synopsis:
      "The son of Zeus must prove himself worthy of his place among the gods by completing a series of legendary labors.",
    director: "Brett Ratner",
    cast: ["Dwayne Johnson", "Ian McShane", "Rufus Sewell"],
    releaseDate: "2025-07-25",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "10",
    title: "Wonder Woman 1984",
    slug: slugify("Wonder Woman 1984"),
    genre: "Action",
    rating: 0,
    duration: 0,
    src: "https://m.media-amazon.com/images/I/51D-7LjfJiL._AC_UF894,1000_QL80_.jpg",
    synopsis:
      "Diana must face two new foes as she navigates the Cold War era of the 1980s while protecting the world from a powerful artifact.",
    director: "Patty Jenkins",
    cast: ["Gal Gadot", "Chris Pine", "Kristen Wiig", "Pedro Pascal"],
    releaseDate: "2025-12-25",
    ageRating: "PG-13",
    language: "English",
  },
  {
    id: "11",
    title: "Shang-Chi and the Legend of the Ten Rings",
    slug: slugify("Shang-Chi and the Legend of the Ten Rings"),
    genre: "Action",
    rating: 0,
    duration: 0,
    src: "https://m.media-amazon.com/images/I/71M9kkXbmSL._AC_UF894,1000_QL80_.jpg",
    synopsis:
      "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    director: "Destin Daniel Cretton",
    cast: ["Simu Liu", "Awkwafina", "Tony Leung"],
    releaseDate: "2025-11-05",
    ageRating: "PG-13",
    language: "English",
  },
];

export const ALL_MOVIES: Movie[] = [...NOW_SHOWING, ...COMING_SOON];
