import type { UpcomingTicket, PastTicket } from "./types";

export const UPCOMING: UpcomingTicket[] = [
  {
    id: "OBL-4F1-B2",
    status: "failed",
    movie: "Oblivion",
    datetime: "Today, 7:30 PM",
    cinema: "PrimeSeat Thủ Đức",
    location: "216 Võ Văn Ngân, TP. Thủ Đức, TP.HCM",
    format: "IMAX",
    seats: "H12, H13",
    seatPrice: "210,000₫",
    seatClass: "Standard",
    poster: "https://m.media-amazon.com/images/I/71PcjyqrHBL.jpg",
    totalPrice: "420,000₫",
    paymentMethod: "Via VNPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Coca-Cola", price: "30,000₫", qty: 2 },
    ],
  },
  {
    id: "OPP-9X2-A1",
    status: "success",
    movie: "Oppenheimer",
    datetime: "Fri, Nov 10, 8:00 PM",
    cinema: "PrimeSeat Quận 1",
    location: "135 Nguyễn Huệ, Q.1, TP.HCM",
    format: "IMAX 2D",
    seats: "G12, G13",
    seatPrice: "125,000₫",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
    screen: "Screen 4",
    seatClass: "VIP",
    ageRating: "PG-13",
    totalPrice: "350,000₫",
    paymentMethod: "Via VNPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Coca-Cola", price: "30,000₫", qty: 2 },
      { name: "Nachos", price: "55,000₫", qty: 1 },
    ],
  },
  {
    id: "INI-3K8-D4",
    status: "pending",
    movie: "Inception",
    datetime: "Sat, Nov 18, 6:00 PM",
    cinema: "PrimeSeat Gò Vấp",
    location: "19 Quang Trung, Q. Gò Vấp, TP.HCM",
    format: "Dolby Atmos",
    seats: "G08, G09",
    seatPrice: "190,000₫",
    seatClass: "Standard",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    totalPrice: "380,000₫",
    paymentMethod: "Via MoMo",
  },
  {
    id: "TDK-5M2-E7",
    status: "confirmed",
    movie: "The Dark Knight",
    datetime: "Sun, Nov 19, 7:30 PM",
    cinema: "PrimeSeat Tân Bình",
    location: "11 Cửu Long, Q. Tân Bình, TP.HCM",
    format: "IMAX",
    seats: "K15",
    seatPrice: "300,000₫",
    seatClass: "SweetBox",
    poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
    totalPrice: "300,000₫",
    paymentMethod: "Via ZaloPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Red Wine", price: "120,000₫", qty: 1 },
    ],
  },
  {
    id: "JKR-1N9-F3",
    status: "success",
    movie: "Joker",
    datetime: "Mon, Nov 20, 8:00 PM",
    cinema: "PrimeSeat Bình Tân",
    location: "158 Bùi Tư Toàn, Q. Bình Tân, TP.HCM",
    format: "Standard",
    seats: "F05, F06, F07",
    seatPrice: "150,000₫",
    seatClass: "VIP",
    poster: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280w/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1669120603.jpg?c=2",
    totalPrice: "450,000₫",
    paymentMethod: "Via Cash",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Coca-Cola", price: "30,000₫", qty: 2 },
    ],
  },
  {
    id: "DIV-7P4-G6",
    status: "failed",
    movie: "Divided",
    datetime: "Tue, Nov 21, 9:00 PM",
    cinema: "PrimeSeat Hà Nội",
    location: "282 Đào Tấn, Q. Ba Đình, Hà Nội",
    format: "4DX",
    seats: "A03, A04",
    seatPrice: "260,000₫",
    seatClass: "Standard",
    poster: "https://cdn.dribbble.com/userupload/35223132/file/original-ef853765fc767c6f1d0648662220c2a3.jpg?resize=752x&vertical=center",
    totalPrice: "520,000₫",
    paymentMethod: "Via VNPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Coca-Cola", price: "30,000₫", qty: 2 },
      { name: "Water", price: "15,000₫", qty: 1 },
    ],
  },
];

export const PAST: PastTicket[] = [
  {
    id: "JAWS-3K1-C5",
    status: "used",
    movie: "JAWS",
    format: "IMAX with Laser",
    datetime: "Mar 15, 2024 • 7:30 PM",
    ticketCount: 2,
    poster: "https://m.media-amazon.com/images/I/61pniSbf1FL.jpg",
    cinema: "PrimeSeat Thủ Đức",
    location: "216 Võ Văn Ngân, TP. Thủ Đức, TP.HCM",
    seats: "D05, D06",
    seatPrice: "180,000₫",
    screen: "Screen 2",
    seatClass: "VIP",
    ageRating: "PG-13",
    totalPrice: "360,000₫",
    paymentMethod: "Via VNPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Coca-Cola", price: "30,000₫", qty: 2 },
    ],
  },
  {
    id: "AGT-7M2-D9",
    status: "used",
    movie: "Divided",
    format: "Standard 70mm",
    datetime: "Aug 02, 2023 • 8:15 PM",
    ticketCount: 1,
    poster: "https://cdn.dribbble.com/userupload/35223132/file/original-ef853765fc767c6f1d0648662220c2a3.jpg?resize=752x&vertical=center",
    cinema: "PrimeSeat Hà Nội",
    location: "282 Đào Tấn, Q. Ba Đình, Hà Nội",
    seats: "B10",
    seatPrice: "120,000₫",
    seatClass: "Standard",
    totalPrice: "120,000₫",
    paymentMethod: "Via Cash",
  },
  {
    id: "BP-2R5-E3",
    status: "expired",
    movie: "Black Panther",
    format: "Dolby Cinema",
    datetime: "Nov 10, 2023 • 9:00 PM",
    ticketCount: 2,
    poster: "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_FMjpg_UX1000_.jpg",
    cinema: "PrimeSeat Quận 1",
    location: "135 Nguyễn Huệ, Q.1, TP.HCM",
    seats: "C08, C09",
    seatPrice: "150,000₫",
    screen: "Screen 3",
    seatClass: "VIP",
    ageRating: "PG-13",
    totalPrice: "300,000₫",
    paymentMethod: "Via MoMo",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Water", price: "15,000₫", qty: 2 },
    ],
  },
  {
    id: "INT-8Q6-H2",
    status: "used",
    movie: "Interstellar",
    format: "IMAX 70mm",
    datetime: "Jul 20, 2023 • 6:30 PM",
    ticketCount: 3,
    poster: "/images/hero-interstellar.jpg",
    cinema: "PrimeSeat Gò Vấp",
    location: "19 Quang Trung, Q. Gò Vấp, TP.HCM",
    seats: "A01, A02, A03",
    seatPrice: "200,000₫",
    screen: "Screen 1",
    seatClass: "Standard",
    ageRating: "PG-13",
    totalPrice: "600,000₫",
    paymentMethod: "Via VNPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 2 },
      { name: "Coca-Cola", price: "30,000₫", qty: 3 },
    ],
  },
  {
    id: "AVN-4R1-J8",
    status: "used",
    movie: "Avengers",
    format: "IMAX",
    datetime: "May 15, 2023 • 7:00 PM",
    ticketCount: 2,
    poster: "https://i.ebayimg.com/images/g/wy8AAOSwGMFcv5s2/s-l1200.jpg",
    cinema: "PrimeSeat Tân Bình",
    location: "11 Cửu Long, Q. Tân Bình, TP.HCM",
    seats: "E12, E13",
    seatPrice: "160,000₫",
    seatClass: "SweetBox",
    totalPrice: "320,000₫",
    paymentMethod: "Via ZaloPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Nachos", price: "55,000₫", qty: 1 },
    ],
  },
  {
    id: "DK-9S3-K5",
    status: "expired",
    movie: "The Dark Knight",
    format: "Standard",
    datetime: "Apr 10, 2023 • 8:30 PM",
    ticketCount: 1,
    poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
    cinema: "PrimeSeat Bình Tân",
    location: "158 Bùi Tư Toàn, Q. Bình Tân, TP.HCM",
    seats: "F07",
    seatPrice: "90,000₫",
    seatClass: "Standard",
    totalPrice: "90,000₫",
    paymentMethod: "Via Cash",
  },
  {
    id: "JKR-2T7-L1",
    status: "used",
    movie: "Joker",
    format: "Dolby Atmos",
    datetime: "Mar 05, 2023 • 9:15 PM",
    ticketCount: 2,
    poster: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280w/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1669120603.jpg?c=2",
    cinema: "PrimeSeat Thủ Đức",
    location: "216 Võ Văn Ngân, TP. Thủ Đức, TP.HCM",
    seats: "G04, G05",
    seatPrice: "140,000₫",
    screen: "Screen 5",
    seatClass: "VIP",
    totalPrice: "280,000₫",
    paymentMethod: "Via VNPay",
    foodDrink: [
      { name: "Combo Popcorn", price: "45,000₫", qty: 1 },
      { name: "Coca-Cola", price: "30,000₫", qty: 2 },
    ],
  },
];
