import type { UpcomingTicket, PastTicket } from "./types";

export const UPCOMING: UpcomingTicket[] = [
  {
    id: "OBL-4F1-B2",
    status: "failed",
    movie: "Oblivion",
    datetime: "Today, 7:30 PM",
    cinema: "IMAXr Prime Center",
    format: "IMAX",
    seats: "H12, H13",
    amount: 42.0,
    poster: "https://m.media-amazon.com/images/I/71PcjyqrHBL.jpg",
  },
  {
    id: "OPP-9X2-A1",
    status: "success",
    movie: "Oppenheimer",
    datetime: "Fri, Nov 10, 8:00 PM",
    cinema: "Grand 70mm Theater",
    format: "70mm",
    seats: "J24",
    amount: 35.0,
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg",
  },
  {
    id: "INI-3K8-D4",
    status: "pending",
    movie: "Inception",
    datetime: "Sat, Nov 18, 6:00 PM",
    cinema: "Dolby Cinema Center",
    format: "Dolby Atmos",
    seats: "G08, G09",
    amount: 38.0,
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
  },
  {
    id: "TDK-5M2-E7",
    status: "confirmed",
    movie: "The Dark Knight",
    datetime: "Sun, Nov 19, 7:30 PM",
    cinema: "IMAX Prime Downtown",
    format: "IMAX",
    seats: "K15",
    amount: 30.0,
    poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: "JKR-1N9-F3",
    status: "success",
    movie: "Joker",
    datetime: "Mon, Nov 20, 8:00 PM",
    cinema: "Grand 70mm Theater",
    format: "Standard",
    seats: "F05, F06, F07",
    amount: 45.0,
    poster: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280w/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1669120603.jpg?c=2",
  },
  {
    id: "DIV-7P4-G6",
    status: "failed",
    movie: "Divided",
    datetime: "Tue, Nov 21, 9:00 PM",
    cinema: "PrimeSeat Saigon Centre",
    format: "4DX",
    seats: "A03, A04",
    amount: 52.0,
    poster: "https://cdn.dribbble.com/userupload/35223132/file/original-ef853765fc767c6f1d0648662220c2a3.jpg?resize=752x&vertical=center",
  },
];

export const PAST: PastTicket[] = [
  {
    id: "JAWS-3K1-C5",
    status: "used",
    movie: "JAWS",
    format: "IMAX with Laser",
    datetime: "Mar 15, 2024 • 7:30 PM",
    ticketCount: 2,
    poster: "https://m.media-amazon.com/images/I/61pniSbf1FL.jpg",
  },
  {
    id: "AGT-7M2-D9",
    status: "used",
    movie: "Divided",
    format: "Standard 70mm",
    datetime: "Aug 02, 2023 • 8:15 PM",
    ticketCount: 1,
    poster: "https://cdn.dribbble.com/userupload/35223132/file/original-ef853765fc767c6f1d0648662220c2a3.jpg?resize=752x&vertical=center",
  },
  {
    id: "BP-2R5-E3",
    status: "expired",
    movie: "Black Panther",
    format: "Dolby Cinema",
    datetime: "Nov 10, 2023 • 9:00 PM",
    ticketCount: 2,
    poster: "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: "INT-8Q6-H2",
    status: "used",
    movie: "Interstellar",
    format: "IMAX 70mm",
    datetime: "Jul 20, 2023 • 6:30 PM",
    ticketCount: 3,
    poster: "/images/hero-interstellar.jpg",
  },
  {
    id: "AVN-4R1-J8",
    status: "used",
    movie: "Avengers",
    format: "IMAX",
    datetime: "May 15, 2023 • 7:00 PM",
    ticketCount: 2,
    poster: "https://i.ebayimg.com/images/g/wy8AAOSwGMFcv5s2/s-l1200.jpg",
  },
  {
    id: "DK-9S3-K5",
    status: "expired",
    movie: "The Dark Knight",
    format: "Standard",
    datetime: "Apr 10, 2023 • 8:30 PM",
    ticketCount: 1,
    poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: "JKR-2T7-L1",
    status: "used",
    movie: "Joker",
    format: "Dolby Atmos",
    datetime: "Mar 05, 2023 • 9:15 PM",
    ticketCount: 2,
    poster: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280w/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1669120603.jpg?c=2",
  },
];
